// frontend/app/user/[username]/page.tsx
import Link from "next/link";
import { redirect } from "next/navigation";

import { UserCharts } from "@/components/UserCharts";
import { apiGet } from "@/lib/api";
import { formatDuration, formatNumber, percent, timeAgo, timeChipClass } from "@/lib/format";
import type { UserData } from "@/types/api";

type Props = {
  params: Promise<{ username: string }>;
};

export default async function UserPage({ params }: Props) {
  const { username } = await params;
  const data = await apiGet<UserData>(`/api/next/user/${username}`);
  if (data.redirect) redirect(data.redirect);
  const user = data.User;
  const approvalRate = percent(data.ReviewerStats?.Approvals, data.ReviewerStats?.TotalReviews);

  return (
    <div className="page-wrap">
      <div className="user-header">
        {user.AvatarURL ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={user.AvatarURL} className="user-avatar" alt={`@${user.Login}`} />
        ) : null}
        <div className="user-info">
          <h1 className="page-title">
            {user.Name || `@${user.Login}`}
            {data.IsNGMI ? <span className="ngmi-stamp">ngmi</span> : null}
          </h1>
          <p className="user-login mono">@{user.Login}</p>
          {user.Bio ? <p className="user-bio">{user.Bio}</p> : null}
          <div className="user-meta">
            {user.Company ? <span className="meta-item">{user.Company}</span> : null}
            {user.Location ? <span className="meta-item">{user.Location}</span> : null}
            {user.Followers ? <span className="meta-item">{formatNumber(user.Followers)} followers</span> : null}
            {user.PublicRepos ? <span className="meta-item">{formatNumber(user.PublicRepos)} repos</span> : null}
            {data.ReviewerStats?.LastReviewedAt ? <span className="meta-item muted">last reviewed {timeAgo(data.ReviewerStats.LastReviewedAt)}</span> : null}
          </div>
        </div>
        <a href={`https://github.com/${user.Login}`} target="_blank" rel="noopener" className="btn btn-outline">
          GitHub ↗
        </a>
      </div>

      {!data.ReviewerStats?.TotalReviews ? (
        <div className="verdict-card verdict-shame">
          <p className="verdict-text">No reviews on record. ngmi.</p>
        </div>
      ) : (
        <div className="verdict-card">
          <p className="verdict-text">
            {data.ReviewerRank ? `#${data.ReviewerRank} globally - ` : ""}
            {formatNumber(data.ReviewerStats.TotalReviews)} reviews, {approvalRate}% approval rate.
          </p>
          {data.ShareURL ? (
            <div className="verdict-actions">
              <a href={data.ShareURL} target="_blank" rel="noopener" className="btn btn-sm btn-outline">
                Share on X →
              </a>
            </div>
          ) : null}
        </div>
      )}

      {data.ReviewerRank || data.GatekeeperRank || data.AuthorRank ? (
        <div className="rank-banner">
          {data.ReviewerRank ? (
            <div className="rank-pill">
              <Link href="/leaderboard/reviewers">#{data.ReviewerRank} Reviewer</Link>
              <span className="rank-pill-sub">globally</span>
            </div>
          ) : null}
          {data.GatekeeperRank ? (
            <div className="rank-pill warn">
              <Link href="/leaderboard/gatekeepers">#{data.GatekeeperRank} Gatekeeper</Link>
              <span className="rank-pill-sub">globally</span>
            </div>
          ) : null}
          {data.AuthorRank ? (
            <div className="rank-pill">
              <Link href="/leaderboard/authors">#{data.AuthorRank} Author</Link>
              <span className="rank-pill-sub">globally</span>
            </div>
          ) : null}
        </div>
      ) : null}

      <div className="two-col">
        <div className="col-card">
          <h2 className="col-title">As a Reviewer</h2>
          {data.ReviewerStats ? (
            <>
              <div className="col-stats">
                <Metric label="Total Reviews" value={formatNumber(data.ReviewerStats.TotalReviews)} />
                <Metric label="Approvals" value={formatNumber(data.ReviewerStats.Approvals)} className="green" />
                <Metric label="Changes Requested" value={formatNumber(data.ReviewerStats.ChangesRequested)} className="warn" />
                <Metric label="Comments" value={formatNumber(data.ReviewerStats.Comments)} className="muted" />
              </div>
              {data.ReviewerStats.TotalReviews ? (
                <div className="approval-bar-wrap">
                  <div className="approval-bar">
                    <div className="approval-fill" style={{ width: `${approvalRate}%` }} />
                  </div>
                  <span className="approval-label">{approvalRate}% approval rate</span>
                </div>
              ) : null}
            </>
          ) : (
            <p className="col-empty">No review data yet for this user.</p>
          )}
        </div>

        <div className="col-card">
          <h2 className="col-title">As an Author</h2>
          {data.AuthorStats ? (
            <div className="col-stats">
              <Metric label="Merged PRs" value={formatNumber(data.AuthorStats.MergedPRs)} />
              <Metric label="Avg Merge Time" value={formatDuration(data.AuthorStats.AvgMergeTimeSecs)} className="speed" />
              {data.AuthorStats.TotalPRs ? <Metric label="Merge Rate" value={`${percent(data.AuthorStats.MergedPRs, data.AuthorStats.TotalPRs)}%`} /> : null}
              {data.AuthorStats.TotalLinesWritten ? <Metric label="Total Lines Written" value={formatNumber(data.AuthorStats.TotalLinesWritten)} /> : null}
              {data.AuthorStats.AvgPRSize ? <Metric label="Avg PR Size" value={formatNumber(Math.round(data.AuthorStats.AvgPRSize))} /> : null}
              {data.AuthorStats.CleanApprovalRate ? <Metric label="Clean Approval Rate" value={`${Math.round(data.AuthorStats.CleanApprovalRate)}%`} className="green" /> : null}
              {data.AuthorStats.AvgChangesRequested ? <Metric label="Avg Changes Requested" value={`${data.AuthorStats.AvgChangesRequested.toFixed(1)}x`} className="warn" /> : null}
            </div>
          ) : (
            <p className="col-empty">No PR author data yet for this user.</p>
          )}
        </div>
      </div>

      {data.FastestPR || data.SlowestPR ? (
        <section className="section">
          <h2 className="section-title">Personal Records</h2>
          <div className="two-col">
            {data.FastestPR ? <Record title="Fastest Merge" tone="speed" pr={data.FastestPR} /> : null}
            {data.SlowestPR ? <Record title="Slowest Merge" tone="slow" pr={data.SlowestPR} /> : null}
          </div>
        </section>
      ) : null}

      <UserCharts username={user.Login} />

      {data.ReviewersOfMe?.length || data.AuthorsIReview?.length ? (
        <section className="section">
          <h2 className="section-title">Collaborators</h2>
          <div className="two-col">
            <PeopleList title="Reviews my PRs most" people={data.ReviewersOfMe} suffix="reviews" />
            <PeopleList title="I review most" people={data.AuthorsIReview} suffix="reviews" />
          </div>
        </section>
      ) : null}

      {data.ReviewedRepos?.length ? (
        <section className="section">
          <h2 className="section-title">Repos Reviewed Most</h2>
          <table className="pr-table">
            <thead>
              <tr>
                <th>Repository</th>
                <th>Reviews Given</th>
              </tr>
            </thead>
            <tbody>
              {data.ReviewedRepos.map((repo) => (
                <tr className="pr-row" key={repo.FullName}>
                  <td>
                    <Link href={`/repo/${repo.FullName}`} className="pr-link mono">
                      {repo.FullName}
                    </Link>
                  </td>
                  <td>{formatNumber(repo.Count)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ) : null}

      {data.ContributedRepos?.length ? (
        <section className="section">
          <h2 className="section-title">Repos Contributed To</h2>
          <table className="pr-table">
            <thead>
              <tr>
                <th>Repository</th>
                <th>Merged PRs</th>
                <th>Avg Merge Time</th>
                <th>Fastest</th>
              </tr>
            </thead>
            <tbody>
              {data.ContributedRepos.map((repo) => (
                <tr className="pr-row" key={repo.FullName}>
                  <td>
                    <Link href={`/repo/${repo.FullName}`} className="pr-link mono">
                      {repo.FullName}
                    </Link>
                  </td>
                  <td>{formatNumber(repo.MergedPRCount)}</td>
                  <td>
                    <span className={timeChipClass(repo.AvgMergeTimeSecs)}>{formatDuration(repo.AvgMergeTimeSecs)}</span>
                  </td>
                  <td className="speed">{formatDuration(repo.MinMergeTimeSecs)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ) : null}
    </div>
  );
}

function Metric({ label, value, className = "" }: { label: string; value: string; className?: string }) {
  return (
    <div className="col-stat">
      <span className={`col-stat-num ${className}`}>{value}</span>
      <span className="col-stat-label">{label}</span>
    </div>
  );
}

function Record({ title, tone, pr }: { title: string; tone: "speed" | "slow"; pr: NonNullable<UserData["FastestPR"]> }) {
  return (
    <div className="col-card">
      <h3 className="col-title">{title}</h3>
      <div className="col-stats">
        <Metric label="merge time" value={formatDuration(pr.MergeTimeSecs)} className={tone} />
      </div>
      <a href={`https://github.com/${pr.RepoFullName}/pull/${pr.Number}`} target="_blank" rel="noopener" className="pr-link mono record-pr-title">
        {pr.RepoFullName} #{pr.Number}
      </a>
      <p className="record-pr-desc">{pr.Title}</p>
    </div>
  );
}

function PeopleList({ title, people, suffix }: { title: string; people?: { Login: string; AvatarURL: string; Count: number }[]; suffix: string }) {
  if (!people?.length) return <div className="col-card" />;
  return (
    <div className="col-card">
      <h3 className="col-title">{title}</h3>
      <div className="board-rows">
        {people.map((person, index) => (
          <Link href={`/user/${person.Login}`} className="board-row" key={person.Login}>
            <span className="board-rank">#{index + 1}</span>
            {person.AvatarURL ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={person.AvatarURL} className="board-avatar" alt="" />
            ) : null}
            <span className="board-name mono">@{person.Login}</span>
            <span className="board-val">
              {formatNumber(person.Count)} {suffix}
            </span>
          </Link>
        ))}
      </div>
    </div>
  );
}

// web/src/routes/user/[username]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { Badge } from '$lib/components/ui/badge';
	import { Card, CardHeader, CardTitle, CardContent } from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '$lib/components/ui/table';
	import * as Chart from '$lib/components/ui/chart/index.js';
	import { LineChart, BarChart } from 'layerchart';
	import { formatDuration, formatNumber, rankClass } from '$lib/utils';
	import { toRows } from '$lib/types';
	import type { User } from '$lib/types';

	let { data } = $props();
	const d = $derived(data.user);
	const user: User = $derived(d?.User);
	const username = $derived($page.params.username);

	const activityData = $derived(
		d?.ActivityChart?.labels
			? toRows(d.ActivityChart.labels, {
					prCounts: d.ActivityChart.prCounts,
					reviewCounts: d.ActivityChart.reviewCounts
				})
			: []
	);

	const sizeBucketData = $derived(
		d?.SizeBucketChart?.labels
			? toRows(d.SizeBucketChart.labels, { prCounts: d.SizeBucketChart.prCounts })
			: []
	);

	const activityConfig = {
		prCounts: { label: 'PRs', color: 'var(--chart-1)' },
		reviewCounts: { label: 'Reviews', color: 'var(--chart-2)' }
	} satisfies Chart.ChartConfig;

	const sizeConfig = {
		prCounts: { label: 'PRs', color: 'var(--chart-1)' }
	} satisfies Chart.ChartConfig;
</script>

<svelte:head>
	<title>@{username} — ngmi</title>
</svelte:head>

<!-- Breadcrumb -->
<div class="mb-3 flex items-center gap-1 text-xs text-muted-foreground">
	<a href="/" class="hover:text-foreground">ngmi</a>
	<span>/</span>
	<span class="text-foreground">@{username}</span>
</div>

<!-- Header -->
<div class="mb-6 flex items-start gap-4">
	{#if user?.AvatarURL}
		<img src={user.AvatarURL} alt="" class="size-16 rounded-full" />
	{/if}
	<div class="min-w-0 flex-1">
		<div class="mb-1 flex flex-wrap items-center gap-2">
			<h1 class="font-mono text-base font-bold">@{user?.Login ?? username}</h1>
			{#if d?.IsNGMI}
				<Badge variant="destructive">ngmi</Badge>
			{/if}
		</div>
		{#if user?.Name}
			<p class="text-sm">{user.Name}</p>
		{/if}
		{#if user?.Bio}
			<p class="text-xs text-muted-foreground">{user.Bio}</p>
		{/if}
		<div class="mt-1 flex flex-wrap gap-3 text-xs text-muted-foreground">
			{#if user?.Company}<span>{user.Company}</span>{/if}
			{#if user?.Location}<span>{user.Location}</span>{/if}
			{#if user?.Followers}<span>{formatNumber(user.Followers)} followers</span>{/if}
		</div>
		{#if d?.ShareURL}
			<div class="mt-2">
				<a href={d.ShareURL} target="_blank" rel="noopener">
					<Button size="sm" variant="outline">Share on X →</Button>
				</a>
			</div>
		{/if}
	</div>
</div>

<!-- Rank badges -->
{#if d?.ReviewerRank || d?.GatekeeperRank || d?.AuthorRank}
	<div class="mb-6 flex flex-wrap gap-2">
		{#if d.ReviewerRank}<Badge variant="secondary" class="font-mono">#{d.ReviewerRank} Reviewer</Badge>{/if}
		{#if d.GatekeeperRank}<Badge variant="secondary" class="font-mono">#{d.GatekeeperRank} Gatekeeper</Badge>{/if}
		{#if d.AuthorRank}<Badge variant="secondary" class="font-mono">#{d.AuthorRank} Author</Badge>{/if}
	</div>
{/if}

<!-- Stats grid -->
<div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
	{#if d?.ReviewerStats}
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold">{formatNumber(d.ReviewerStats.TotalReviews)}</div>
				<div class="text-xs text-muted-foreground">Reviews</div>
			</CardContent>
		</Card>
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold text-green-400">{formatNumber(d.ReviewerStats.Approvals)}</div>
				<div class="text-xs text-muted-foreground">Approvals</div>
			</CardContent>
		</Card>
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold text-red-400">{formatNumber(d.ReviewerStats.ChangesRequested)}</div>
				<div class="text-xs text-muted-foreground">Blocks</div>
			</CardContent>
		</Card>
	{/if}
	{#if d?.AuthorStats}
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold">{formatNumber(d.AuthorStats.MergedPRs)}</div>
				<div class="text-xs text-muted-foreground">Merged PRs</div>
			</CardContent>
		</Card>
		{#if d.AuthorStats.AvgMergeTimeSecs}
			<Card class="text-center">
				<CardContent class="pt-4 pb-3">
					<div class="text-xl font-bold">{formatDuration(d.AuthorStats.AvgMergeTimeSecs)}</div>
					<div class="text-xs text-muted-foreground">Avg Merge Time</div>
				</CardContent>
			</Card>
		{/if}
		{#if d.AuthorStats.CleanApprovalRate}
			<Card class="text-center">
				<CardContent class="pt-4 pb-3">
					<div class="text-xl font-bold">{d.AuthorStats.CleanApprovalRate.toFixed(0)}%</div>
					<div class="text-xs text-muted-foreground">Clean PRs</div>
				</CardContent>
			</Card>
		{/if}
	{/if}
</div>

<!-- Activity Chart -->
{#if activityData.length > 0}
	<Card class="mb-6">
		<CardHeader><CardTitle class="text-sm">Activity Over Time</CardTitle></CardHeader>
		<CardContent>
			<Chart.Container config={activityConfig} class="h-40">
				<LineChart
					data={activityData}
					x="label"
					axis={true}
					series={[
						{ key: 'prCounts', label: 'PRs', color: 'var(--chart-1)' },
						{ key: 'reviewCounts', label: 'Reviews', color: 'var(--chart-2)' }
					]}
				>
					{#snippet tooltip()}
						<Chart.Tooltip />
					{/snippet}
				</LineChart>
			</Chart.Container>
		</CardContent>
	</Card>
{/if}

<!-- PR Size Distribution -->
{#if sizeBucketData.length > 0}
	<Card class="mb-6">
		<CardHeader><CardTitle class="text-sm">PR Size Distribution</CardTitle></CardHeader>
		<CardContent>
			<Chart.Container config={sizeConfig} class="h-32">
				<BarChart
					data={sizeBucketData}
					x="label"
					axis="x"
					series={[{ key: 'prCounts', label: 'PRs', color: 'var(--chart-1)' }]}
				>
					{#snippet tooltip()}
						<Chart.Tooltip />
					{/snippet}
				</BarChart>
			</Chart.Container>
		</CardContent>
	</Card>
{/if}

<!-- Record PRs -->
{#if d?.FastestPR || d?.SlowestPR}
	<div class="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2">
		{#if d.FastestPR}
			<Card>
				<CardHeader class="pb-2"><CardTitle class="text-xs text-green-400">Fastest PR</CardTitle></CardHeader>
				<CardContent class="text-xs">
					<a href="https://github.com/{d.FastestPR.RepoFullName}/pull/{d.FastestPR.Number}" target="_blank" rel="noopener" class="font-medium hover:underline">{d.FastestPR.Title}</a>
					<div class="mt-1 text-muted-foreground">{d.FastestPR.RepoFullName} · {formatDuration(d.FastestPR.MergeTimeSecs)}</div>
				</CardContent>
			</Card>
		{/if}
		{#if d.SlowestPR}
			<Card>
				<CardHeader class="pb-2"><CardTitle class="text-xs text-red-400">Slowest PR</CardTitle></CardHeader>
				<CardContent class="text-xs">
					<a href="https://github.com/{d.SlowestPR.RepoFullName}/pull/{d.SlowestPR.Number}" target="_blank" rel="noopener" class="font-medium hover:underline">{d.SlowestPR.Title}</a>
					<div class="mt-1 text-muted-foreground">{d.SlowestPR.RepoFullName} · {formatDuration(d.SlowestPR.MergeTimeSecs)}</div>
				</CardContent>
			</Card>
		{/if}
	</div>
{/if}

<!-- Reviewed Repos -->
{#if d?.ReviewedRepos?.length > 0}
	<Card class="mb-6">
		<CardHeader><CardTitle class="text-sm">Top Reviewed Repos</CardTitle></CardHeader>
		<CardContent class="space-y-1">
			{#each d.ReviewedRepos as rr}
				<a href="/repo/{rr.FullName}" class="flex items-center justify-between rounded p-1.5 text-xs hover:bg-accent">
					<span class="font-mono">{rr.FullName}</span>
					<Badge variant="secondary">{rr.Count} reviews</Badge>
				</a>
			{/each}
		</CardContent>
	</Card>
{/if}

<!-- Collaborated With -->
{#if (d?.ReviewersOfMe?.length ?? 0) > 0 || (d?.AuthorsIReview?.length ?? 0) > 0}
	<div class="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2">
		{#if d?.ReviewersOfMe?.length > 0}
			<Card>
				<CardHeader><CardTitle class="text-sm">Reviewed My PRs</CardTitle></CardHeader>
				<CardContent class="space-y-1">
					{#each d.ReviewersOfMe as c}
						<a href="/user/{c.Login}" class="flex items-center gap-2 rounded p-1 text-xs hover:bg-accent">
							{#if c.AvatarURL}<img src={c.AvatarURL} alt="" class="size-5 rounded-full" />{/if}
							<span class="flex-1 font-mono">@{c.Login}</span>
							<Badge variant="secondary">{c.Count}x</Badge>
						</a>
					{/each}
				</CardContent>
			</Card>
		{/if}
		{#if d?.AuthorsIReview?.length > 0}
			<Card>
				<CardHeader><CardTitle class="text-sm">Authors I Review</CardTitle></CardHeader>
				<CardContent class="space-y-1">
					{#each d.AuthorsIReview as c}
						<a href="/user/{c.Login}" class="flex items-center gap-2 rounded p-1 text-xs hover:bg-accent">
							{#if c.AvatarURL}<img src={c.AvatarURL} alt="" class="size-5 rounded-full" />{/if}
							<span class="flex-1 font-mono">@{c.Login}</span>
							<Badge variant="secondary">{c.Count}x</Badge>
						</a>
					{/each}
				</CardContent>
			</Card>
		{/if}
	</div>
{/if}

<!-- Contributed Repos -->
{#if d?.ContributedRepos?.length > 0}
	<Card>
		<CardHeader><CardTitle class="text-sm">Contributed Repos</CardTitle></CardHeader>
		<CardContent class="overflow-x-auto p-0">
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead>Repo</TableHead>
						<TableHead class="w-24">Merged PRs</TableHead>
						<TableHead class="w-28">Avg Time</TableHead>
					</TableRow>
				</TableHeader>
				<TableBody>
					{#each d.ContributedRepos as repo}
						<TableRow>
							<TableCell class="font-mono text-xs">
								<a href="/repo/{repo.FullName}" class="hover:underline">{repo.FullName}</a>
							</TableCell>
							<TableCell class="text-xs">{formatNumber(repo.MergedPRCount)}</TableCell>
							<TableCell class="text-xs">{repo.AvgMergeTimeSecs ? formatDuration(repo.AvgMergeTimeSecs) : '—'}</TableCell>
						</TableRow>
					{/each}
				</TableBody>
			</Table>
		</CardContent>
	</Card>
{/if}
