// web/src/routes/leaderboard/[category]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Card, CardHeader, CardTitle, CardContent } from '$lib/components/ui/card';
	import {
		Table,
		TableBody,
		TableCell,
		TableHead,
		TableHeader,
		TableRow
	} from '$lib/components/ui/table';
	import { formatDuration, formatNumber, rankClass } from '$lib/utils';
	import type { RepoLeaderboardRow, UserLeaderboardRow, CleanLeaderboardRow } from '$lib/types';

	let { data } = $props();
	const d = $derived(data.leaderboard);
	const category = $derived($page.params.category);

	const isUserCategory = $derived(
		category === 'reviewers' || category === 'gatekeepers' || category === 'authors'
	);
	const isCleanCategory = $derived(category === 'oneshot');

	let searchQuery = $state('');
	let searchResults = $state<{ RepoRows: RepoLeaderboardRow[]; UserRows: UserLeaderboardRow[] } | null>(null);
	let searching = $state(false);
	let searchTimer: ReturnType<typeof setTimeout>;

	function onSearch(e: Event) {
		const val = (e.target as HTMLInputElement).value;
		searchQuery = val;
		clearTimeout(searchTimer);
		if (!val.trim()) {
			searchResults = null;
			return;
		}
		searchTimer = setTimeout(async () => {
			searching = true;
			try {
				const r = await fetch(
					`/api/v1/leaderboard/${category}/search?q=${encodeURIComponent(val)}`
				);
				searchResults = await r.json();
			} catch {
				searchResults = null;
			} finally {
				searching = false;
			}
		}, 300);
	}

	const displayRepoRows = $derived(searchResults?.RepoRows ?? d?.RepoRows ?? []);
	const displayUserRows = $derived(searchResults?.UserRows ?? d?.UserRows ?? []);
	const displayCleanRows = $derived(d?.CleanRows ?? []);
</script>

<svelte:head>
	<title>{d?.Title ?? category} — ngmi</title>
</svelte:head>

<!-- Breadcrumb -->
<div class="mb-3 flex items-center gap-1 text-xs text-muted-foreground">
	<a href="/" class="hover:text-foreground">ngmi</a>
	<span>/</span>
	<span class="text-foreground">Leaderboard</span>
	<span>/</span>
	<span class="text-foreground">{d?.Title ?? category}</span>
</div>

<!-- Header -->
<div class="mb-6">
	<h1 class="mb-1 text-base font-bold">{d?.Title}</h1>
	{#if d?.Description}
		<p class="text-xs text-muted-foreground">{d.Description}</p>
	{/if}
</div>

<!-- Search -->
<div class="mb-4 max-w-sm">
	<Input
		type="text"
		placeholder={isUserCategory ? 'Search by username…' : 'Search by repo…'}
		class="font-mono text-xs"
		oninput={onSearch}
	/>
</div>

{#if isCleanCategory}
	<!-- Clean leaderboard -->
	<Card>
		<CardContent class="overflow-x-auto p-0">
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead class="w-12">Rank</TableHead>
						<TableHead>Repo</TableHead>
						<TableHead class="w-20">Clean %</TableHead>
						<TableHead class="w-20">Total PRs</TableHead>
						<TableHead class="w-28">Avg Time</TableHead>
					</TableRow>
				</TableHeader>
				<TableBody>
					{#each displayCleanRows as row}
						<TableRow>
							<TableCell class="font-mono text-xs {rankClass(row.Rank)}">#{row.Rank}</TableCell>
							<TableCell class="font-mono text-xs">
								<a href="/repo/{row.FullName}" class="hover:underline">{row.FullName}</a>
							</TableCell>
							<TableCell class="text-xs text-green-400">{row.CleanPct.toFixed(0)}%</TableCell>
							<TableCell class="text-xs">{formatNumber(row.Total)}</TableCell>
							<TableCell class="text-xs">{formatDuration(row.AvgSecs)}</TableCell>
						</TableRow>
					{/each}
				</TableBody>
			</Table>
		</CardContent>
	</Card>
{:else if isUserCategory}
	<!-- User leaderboard -->
	<Card>
		<CardContent class="overflow-x-auto p-0">
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead class="w-12">Rank</TableHead>
						<TableHead>User</TableHead>
						{#if category === 'reviewers'}
							<TableHead class="w-24">Reviews</TableHead>
							<TableHead class="w-20">Approvals</TableHead>
							<TableHead class="w-20">Blocks</TableHead>
						{:else if category === 'gatekeepers'}
							<TableHead class="w-24">Blocks</TableHead>
						{:else}
							<TableHead class="w-24">Merged PRs</TableHead>
							<TableHead class="w-28">Avg Time</TableHead>
						{/if}
					</TableRow>
				</TableHeader>
				<TableBody>
					{#each displayUserRows as row}
						<TableRow>
							<TableCell class="font-mono text-xs {rankClass(row.Rank)}">#{row.Rank}</TableCell>
							<TableCell class="text-xs">
								<a href="/user/{row.Login}" class="flex items-center gap-2 hover:underline">
									{#if row.AvatarURL}
										<img src={row.AvatarURL} alt="" class="size-5 rounded-full" />
									{/if}
									<span class="font-mono">@{row.Login}</span>
								</a>
							</TableCell>
							{#if category === 'reviewers'}
								<TableCell class="text-xs">{formatNumber(row.Total)}</TableCell>
								<TableCell class="text-xs text-green-400">{formatNumber(row.Approvals)}</TableCell>
								<TableCell class="text-xs text-red-400">{formatNumber(row.ChangesRequested)}</TableCell>
							{:else if category === 'gatekeepers'}
								<TableCell class="text-xs text-red-400">{formatNumber(row.ChangesRequested)}</TableCell>
							{:else}
								<TableCell class="text-xs">{formatNumber(row.MergedPRs)}</TableCell>
								<TableCell class="text-xs">
									{#if row.AvgMergeTimeSecs}
										{formatDuration(row.AvgMergeTimeSecs)}
									{:else}
										—
									{/if}
								</TableCell>
							{/if}
						</TableRow>
					{/each}
				</TableBody>
			</Table>
		</CardContent>
	</Card>
{:else}
	<!-- Repo leaderboard -->
	<Card>
		<CardContent class="overflow-x-auto p-0">
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead class="w-12">Rank</TableHead>
						<TableHead>Repo</TableHead>
						<TableHead class="w-28">Avg Time</TableHead>
						<TableHead class="w-24">PRs</TableHead>
					</TableRow>
				</TableHeader>
				<TableBody>
					{#each displayRepoRows as row}
						<TableRow>
							<TableCell class="font-mono text-xs {rankClass(row.Rank)}">#{row.Rank}</TableCell>
							<TableCell class="font-mono text-xs">
								<a href="/repo/{row.FullName}" class="hover:underline">{row.FullName}</a>
							</TableCell>
							<TableCell class="text-xs">
								<Badge
									variant={row.AvgSecs < 86400 ? 'outline' : 'secondary'}
									class={row.AvgSecs < 86400 ? 'text-green-400' : row.AvgSecs > 2592000 ? 'text-red-400' : ''}
								>
									{formatDuration(row.AvgSecs)}
								</Badge>
							</TableCell>
							<TableCell class="text-xs">{formatNumber(row.PRCount)}</TableCell>
						</TableRow>
					{/each}
				</TableBody>
			</Table>
		</CardContent>
	</Card>
{/if}

<!-- Pagination -->
{#if !searchQuery && (d?.HasMore || d?.NextOffset > 0)}
	<div class="mt-4 flex justify-center gap-2">
		{#if d.NextOffset > 50}
			<Button variant="outline" size="sm" onclick={() => history.back()}>← Prev</Button>
		{/if}
		{#if d.HasMore}
			<a href="?offset={d.NextOffset}">
				<Button variant="outline" size="sm">Next →</Button>
			</a>
		{/if}
	</div>
{/if}

// frontend/app/leaderboard/[category]/page.tsx
import Link from "next/link";

import { LeaderboardSearch } from "@/components/LeaderboardSearch";
import { apiGet, qs } from "@/lib/api";
import { formatDuration, formatNumber, percent, rankBadge, rankClass, timeChipClass } from "@/lib/format";
import type { LeaderboardPageData } from "@/types/api";

type Props = {
  params: Promise<{ category: string }>;
  searchParams: Promise<{ offset?: string }>;
};

export default async function LeaderboardPage({ params, searchParams }: Props) {
  const { category } = await params;
  const sp = await searchParams;
  const offset = Number(sp.offset || 0);
  const data = await apiGet<LeaderboardPageData>(`/api/next/leaderboard/${category}${qs({ offset })}`);

  return (
    <div className="page-wrap">
      <div className="breadcrumb">
        <Link href="/" className="bc-link">
          ngmi
        </Link>
        <span className="bc-sep">/</span>
        <span className="bc-current">{data.Title}</span>
      </div>

      <div className="lb-page-header">
        <div>
          <h1 className="page-title">{data.Title}</h1>
          <p className="repo-desc">{data.Description}</p>
        </div>
        <Link href="/" className="btn btn-outline">
          Back to leaderboards
        </Link>
      </div>

      <LeaderboardSearch category={category} />

      {data.RepoRows?.length ? <RepoTable rows={data.RepoRows} /> : null}
      {data.UserRows?.length && (category === "reviewers" || category === "gatekeepers") ? <ReviewerTable rows={data.UserRows} category={category} /> : null}
      {data.UserRows?.length && category === "authors" ? <AuthorTable rows={data.UserRows} /> : null}
      {data.CleanRows?.length ? <CleanTable rows={data.CleanRows} /> : null}

      {data.HasMore ? (
        <div className="pagination">
          <Link href={`/leaderboard/${category}?offset=${data.NextOffset}`} className="page-btn">
            Next →
          </Link>
        </div>
      ) : null}

      {!data.RepoRows?.length && !data.UserRows?.length && !data.CleanRows?.length ? (
        <div className="empty-state">
          <p>No data yet. Search for repos to populate this leaderboard.</p>
        </div>
      ) : null}
    </div>
  );
}

function RepoTable({ rows }: { rows: LeaderboardPageData["RepoRows"] }) {
  return (
    <div className="pr-table-wrap">
      <table className="pr-table">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Repository</th>
            <th>Avg Time</th>
            <th>Fastest PR</th>
            <th>Slowest PR</th>
            <th>Merged PRs</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr className="pr-row" key={row.FullName}>
              <td><span className={`board-rank ${rankClass(row.Rank)}`}>{rankBadge(row.Rank)}</span></td>
              <td><Link href={`/repo/${row.FullName}`} className="pr-link mono">{row.FullName}</Link></td>
              <td><span className={timeChipClass(row.AvgSecs)}>{formatDuration(row.AvgSecs)}</span></td>
              <td className="speed">{formatDuration(row.MinSecs)}</td>
              <td className="slow">{formatDuration(row.MaxSecs)}</td>
              <td className="muted">{formatNumber(row.PRCount)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function ReviewerTable({ rows, category }: { rows: LeaderboardPageData["UserRows"]; category: string }) {
  return (
    <div className="pr-table-wrap">
      <table className="pr-table">
        <thead>
          <tr>
            <th>Rank</th>
            <th>User</th>
            <th>{category === "reviewers" ? "Total Reviews" : "Changes Requested"}</th>
            <th>Approvals</th>
            <th>Changes Requested</th>
            <th>Approval Rate</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr className="pr-row" key={row.Login}>
              <td><span className={`board-rank ${rankClass(row.Rank)}`}>{rankBadge(row.Rank)}</span></td>
              <td>
                <Link href={`/user/${row.Login}`} className="lb-user-cell">
                  {row.AvatarURL ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={row.AvatarURL} className="reviewer-avatar" alt="" />
                  ) : null}
                  <span className="mono">@{row.Login}</span>
                </Link>
              </td>
              <td className="fw-bold">{formatNumber(row.Total)}</td>
              <td className="green">{formatNumber(row.Approvals)}</td>
              <td className="warn">{formatNumber(row.ChangesRequested)}</td>
              <td className="muted">{row.Total ? `${percent(row.Approvals, row.Total)}%` : "-"}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function AuthorTable({ rows }: { rows: LeaderboardPageData["UserRows"] }) {
  return (
    <div className="pr-table-wrap">
      <table className="pr-table">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Author</th>
            <th>Merged PRs</th>
            <th>Avg Merge Time</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr className="pr-row" key={row.Login}>
              <td><span className={`board-rank ${rankClass(row.Rank)}`}>{rankBadge(row.Rank)}</span></td>
              <td><Link href={`/user/${row.Login}`} className="lb-user-cell">@{row.Login}</Link></td>
              <td className="fw-bold">{formatNumber(row.MergedPRs)}</td>
              <td>{row.AvgMergeTimeSecs ? <span className={timeChipClass(row.AvgMergeTimeSecs)}>{formatDuration(row.AvgMergeTimeSecs)}</span> : "-"}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function CleanTable({ rows }: { rows: LeaderboardPageData["CleanRows"] }) {
  return (
    <div className="pr-table-wrap">
      <table className="pr-table">
        <thead>
          <tr>
            <th>Rank</th>
            <th>Repository</th>
            <th>Clean Rate</th>
            <th>Avg Merge Time</th>
            <th>Total PRs</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr className="pr-row" key={row.FullName}>
              <td><span className={`board-rank ${rankClass(row.Rank)}`}>{rankBadge(row.Rank)}</span></td>
              <td><Link href={`/repo/${row.FullName}`} className="pr-link mono">{row.FullName}</Link></td>
              <td><span className="clean-rate-chip">{row.CleanPct}% approved first try</span></td>
              <td>{formatDuration(row.AvgSecs)}</td>
              <td className="muted">{formatNumber(row.Total)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
