// frontend/app/stats/page.tsx
import { TimeCharts, ChartBlock, type TimePayload } from "@/components/Charts";
import { apiGet, qs } from "@/lib/api";
import { formatDuration, formatNumber, jsonPayload } from "@/lib/format";
import type { StatsData } from "@/types/api";

type Props = {
  searchParams: Promise<{ trim?: string; min_stars?: string; min_contribs?: string }>;
};

type SizePayload = {
  labels?: string[];
  prCounts?: number[];
  avgHours?: number[];
  medianHours?: number[];
  approvalRate?: number[];
  changesRequestedRate?: number[];
  avgChangesRequested?: number[];
};

export default async function StatsPage({ searchParams }: Props) {
  const sp = await searchParams;
  const trim = Number(sp.trim || 0);
  const minStars = Number(sp.min_stars || 0);
  const minContribs = Number(sp.min_contribs || 0);
  const data = await apiGet<StatsData>(`/api/next/stats${qs({ trim, min_stars: minStars, min_contribs: minContribs })}`);
  const size = jsonPayload<SizePayload>(data.SizeChartJSON);
  const time = jsonPayload<TimePayload>(data.TimeChartJSON);

  return (
    <div className="page-wrap">
      <div className="breadcrumb">
        <a href="/" className="bc-link">
          ngmi
        </a>
        <span className="bc-sep">/</span>
        <span className="bc-current">stats</span>
      </div>

      <div className="repo-header">
        <div className="repo-title-row">
          <h1 className="page-title mono">Global PR Stats</h1>
        </div>
        <p className="repo-desc">Aggregate review data across all tracked repos.</p>
      </div>

      <div className="stats-grid">
        <Stat label="Merged PRs" value={formatNumber(data.Overall.TotalPRs)} />
        <Stat label="Repos Tracked" value={formatNumber(data.Overall.TotalRepos)} />
        <Stat label="Avg Review Time" value={formatDuration(data.Overall.AvgSecs)} />
        <Stat label="Median Review Time" value={formatDuration(data.Overall.MedianSecs)} className="highlight" />
      </div>

      <form className="chart-controls" action="/stats">
        <div className="trim-ctrl">
          <span>Trim top</span>
          <output>{trim}</output>
          <span>% outliers</span>
          <input type="range" name="trim" min="0" max="20" defaultValue={trim} />
        </div>
        <label className="filter-group">
          <span>Stars</span>
          <select name="min_stars" className="data-filter-select" defaultValue={minStars}>
            <option value="0">Any</option>
            <option value="100">100+</option>
            <option value="1000">1k+</option>
            <option value="10000">10k+</option>
          </select>
        </label>
        <label className="filter-group">
          <span>Contributors</span>
          <select name="min_contribs" className="data-filter-select" defaultValue={minContribs}>
            <option value="0">Any</option>
            <option value="5">5+</option>
            <option value="20">20+</option>
            <option value="100">100+</option>
          </select>
        </label>
        <button className="range-btn active" type="submit">
          Apply
        </button>
      </form>

      <TimeCharts payload={time} includeOpened />

      {size?.labels?.length ? (
        <section className="section">
          <h2 className="section-title">PR Size Buckets</h2>
          <div className="charts-grid charts-grid-2">
            <ChartBlock id="size-time" label="Review time by PR size (hrs)" labels={size.labels} ySuffix="h" series={[{ label: "Avg", data: size.avgHours || [], color: "#d29922" }, { label: "Median", data: size.medianHours || [], color: "#f0883e" }]} />
            <ChartBlock id="size-approval" label="Clean approval rate by PR size (%)" labels={size.labels} ySuffix="%" series={[{ label: "Clean approval", data: size.approvalRate || [], color: "#3fb950", fill: true }]} />
            <ChartBlock id="size-changes" label="Changes requested rate by PR size (%)" labels={size.labels} ySuffix="%" series={[{ label: "Changes requested", data: size.changesRequestedRate || [], color: "#f85149", fill: true }]} />
            <ChartBlock id="size-counts" label="PR count by size" labels={size.labels} type="bar" series={[{ label: "PRs", data: size.prCounts || [], color: "#58a6ff", fill: true }]} />
          </div>
        </section>
      ) : null}
    </div>
  );
}

function Stat({ label, value, className = "" }: { label: string; value: string; className?: string }) {
  return (
    <div className={`stat-card ${className}`}>
      <span className="stat-card-num">{value}</span>
      <span className="stat-card-label">{label}</span>
    </div>
  );
}

// web/src/routes/stats/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { Card, CardHeader, CardTitle, CardContent } from '$lib/components/ui/card';
	import * as Chart from '$lib/components/ui/chart/index.js';
	import { LineChart, BarChart } from 'layerchart';
	import { formatDuration, formatNumber } from '$lib/utils';
	import { toRows } from '$lib/types';

	let { data } = $props();
	const d = $derived(data.stats);

	let minStars = $state(parseInt($page.url.searchParams.get('min_stars') ?? '0'));
	let minContribs = $state(parseInt($page.url.searchParams.get('min_contribs') ?? '0'));

	function applyFilters() {
		goto(`?min_stars=${minStars}&min_contribs=${minContribs}`, { invalidateAll: true });
	}

	const timeData = $derived(
		d?.TimeChart?.labels
			? toRows(d.TimeChart.labels, {
					avgHours: d.TimeChart.avgHours,
					medianHours: d.TimeChart.medianHours
				})
			: []
	);

	const sizeData = $derived(
		d?.SizeChart?.labels
			? toRows(d.SizeChart.labels, {
					avgHours: d.SizeChart.avgHours,
					medianHours: d.SizeChart.medianHours
				})
			: []
	);

	const timeChartConfig = {
		avgHours: { label: 'Avg', color: 'var(--chart-1)' },
		medianHours: { label: 'Median', color: 'var(--chart-2)' }
	} satisfies Chart.ChartConfig;

	const sizeChartConfig = {
		avgHours: { label: 'Avg', color: 'var(--chart-1)' },
		medianHours: { label: 'Median', color: 'var(--chart-2)' }
	} satisfies Chart.ChartConfig;
</script>

<svelte:head>
	<title>Global Stats — ngmi</title>
</svelte:head>

<!-- Breadcrumb -->
<div class="mb-3 flex items-center gap-1 text-xs text-muted-foreground">
	<a href="/" class="hover:text-foreground">ngmi</a>
	<span>/</span>
	<span class="text-foreground">Stats</span>
</div>

<div class="mb-6">
	<h1 class="mb-1 text-base font-bold">Global PR Stats</h1>
	<p class="text-xs text-muted-foreground">Aggregate metrics across all tracked repos.</p>
</div>

<!-- Filters -->
<div class="mb-6 flex flex-wrap items-end gap-3">
	<div>
		<label for="min-stars" class="mb-1 block text-xs text-muted-foreground">Min Stars</label>
		<input id="min-stars" type="number" min="0" bind:value={minStars}
			class="h-8 w-24 rounded border border-border bg-background px-2 text-xs font-mono" />
	</div>
	<div>
		<label for="min-contribs" class="mb-1 block text-xs text-muted-foreground">Min Contributors</label>
		<input id="min-contribs" type="number" min="0" bind:value={minContribs}
			class="h-8 w-24 rounded border border-border bg-background px-2 text-xs font-mono" />
	</div>
	<button onclick={applyFilters} class="h-8 rounded border border-border bg-background px-3 text-xs hover:bg-accent">
		Apply
	</button>
</div>

<!-- Overall stats -->
{#if d?.Overall}
	<div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold">{formatNumber(d.Overall.TotalPRs)}</div>
				<div class="text-xs text-muted-foreground">Total PRs</div>
			</CardContent>
		</Card>
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold">{formatNumber(d.Overall.TotalRepos)}</div>
				<div class="text-xs text-muted-foreground">Repos</div>
			</CardContent>
		</Card>
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold">{formatDuration(d.Overall.AvgSecs)}</div>
				<div class="text-xs text-muted-foreground">Avg Merge Time</div>
			</CardContent>
		</Card>
		<Card class="text-center">
			<CardContent class="pt-4 pb-3">
				<div class="text-xl font-bold">{formatDuration(d.Overall.MedianSecs)}</div>
				<div class="text-xs text-muted-foreground">Median Merge Time</div>
			</CardContent>
		</Card>
	</div>
{/if}

<!-- Time Series Chart -->
{#if timeData.length > 0}
	<Card class="mb-6">
		<CardHeader><CardTitle class="text-sm">Merge Time Over Time (hrs)</CardTitle></CardHeader>
		<CardContent>
			<Chart.Container config={timeChartConfig} class="h-48">
				<LineChart
					data={timeData}
					x="label"
					axis={true}
					series={[
						{ key: 'avgHours', label: 'Avg', color: 'var(--chart-1)' },
						{ key: 'medianHours', label: 'Median', color: 'var(--chart-2)' }
					]}
				>
					{#snippet tooltip()}
						<Chart.Tooltip />
					{/snippet}
				</LineChart>
			</Chart.Container>
		</CardContent>
	</Card>
{/if}

<!-- Size Chart -->
{#if sizeData.length > 0}
	<Card class="mb-6">
		<CardHeader><CardTitle class="text-sm">Avg Merge Time by PR Size (hrs)</CardTitle></CardHeader>
		<CardContent>
			<Chart.Container config={sizeChartConfig} class="h-40">
				<BarChart
					data={sizeData}
					x="label"
					axis="x"
					series={[
						{ key: 'avgHours', label: 'Avg', color: 'var(--chart-1)' },
						{ key: 'medianHours', label: 'Median', color: 'var(--chart-2)' }
					]}
				>
					{#snippet tooltip()}
						<Chart.Tooltip />
					{/snippet}
				</BarChart>
			</Chart.Container>
		</CardContent>
	</Card>
{/if}
