// web/src/routes/org/[org]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { Badge } from '$lib/components/ui/badge';
	import { Card, CardHeader, CardTitle, CardContent } from '$lib/components/ui/card';
	import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '$lib/components/ui/table';
	import * as Chart from '$lib/components/ui/chart/index.js';
	import { LineChart } from 'layerchart';
	import { formatDuration, formatNumber, rankClass } from '$lib/utils';
	import { toRows } from '$lib/types';
	import type { User } from '$lib/types';

	let { data } = $props();
	const d = $derived(data.org);
	const org: User = $derived(d?.Org);
	const orgName = $derived($page.params.org);

	const timeData = $derived(
		d?.TimeChart?.labels
			? toRows(d.TimeChart.labels, {
					avgHours: d.TimeChart.avgHours,
					medianHours: d.TimeChart.medianHours
				})
			: []
	);

	const timeChartConfig = {
		avgHours: { label: 'Avg', color: 'var(--chart-1)' },
		medianHours: { label: 'Median', color: 'var(--chart-2)' }
	} satisfies Chart.ChartConfig;
</script>

<svelte:head>
	<title>@{orgName} — ngmi</title>
</svelte:head>

<!-- Breadcrumb -->
<div class="mb-3 flex items-center gap-1 text-xs text-muted-foreground">
	<a href="/" class="hover:text-foreground">ngmi</a>
	<span>/</span>
	<span class="text-foreground">@{orgName}</span>
</div>

<!-- Header -->
<div class="mb-6 flex items-start gap-4">
	{#if org?.AvatarURL}
		<img src={org.AvatarURL} alt="" class="size-16 rounded-full" />
	{/if}
	<div class="min-w-0 flex-1">
		<div class="mb-1 flex flex-wrap items-center gap-2">
			<h1 class="font-mono text-base font-bold">@{org?.Login ?? orgName}</h1>
			<Badge variant="secondary">Org</Badge>
			{#if d?.IsSyncing}
				<Badge variant="secondary" class="animate-pulse">⟳ Syncing…</Badge>
			{/if}
		</div>
		{#if org?.Name}<p class="text-sm">{org.Name}</p>{/if}
		{#if org?.Bio}<p class="text-xs text-muted-foreground">{org.Bio}</p>{/if}
	</div>
</div>

<!-- Stats -->
<div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3">
	<Card class="text-center">
		<CardContent class="pt-4 pb-3">
			<div class="text-xl font-bold">{formatNumber(d?.Repos?.length ?? 0)}</div>
			<div class="text-xs text-muted-foreground">Repos Tracked</div>
		</CardContent>
	</Card>
	<Card class="text-center">
		<CardContent class="pt-4 pb-3">
			<div class="text-xl font-bold">{formatNumber(d?.TotalMergedPRs ?? 0)}</div>
			<div class="text-xs text-muted-foreground">Merged PRs</div>
		</CardContent>
	</Card>
</div>

<!-- Time Chart -->
{#if timeData.length > 0}
	<Card class="mb-6">
		<CardHeader><CardTitle class="text-sm">Review Time Over Time (hrs)</CardTitle></CardHeader>
		<CardContent>
			<Chart.Container config={timeChartConfig} class="h-48">
				<LineChart
					data={timeData}
					x="label"
					axis={true}
					series={[
						{ key: 'avgHours', label: 'Avg', color: 'var(--chart-1)' },
						{ key: 'medianHours', label: 'Median', color: 'var(--chart-2)' }
					]}
				>
					{#snippet tooltip()}
						<Chart.Tooltip />
					{/snippet}
				</LineChart>
			</Chart.Container>
		</CardContent>
	</Card>
{/if}

<!-- Reviewer & Gatekeeper boards -->
{#if (d?.ReviewerBoard?.length ?? 0) > 0 || (d?.GatekeeperBoard?.length ?? 0) > 0}
	<div class="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
		{#if d?.ReviewerBoard?.length > 0}
			<Card>
				<CardHeader><CardTitle class="text-sm">Top Reviewers</CardTitle></CardHeader>
				<CardContent class="space-y-1">
					{#each d.ReviewerBoard as entry}
						<a href="/user/{entry.Name}" class="flex items-center gap-2 rounded px-1 py-0.5 text-xs hover:bg-accent">
							<span class="w-7 shrink-0 {rankClass(entry.Rank)}">#{entry.Rank}</span>
							{#if entry.Extra}<img src={entry.Extra} alt="" class="size-4 rounded-full" />{/if}
							<span class="flex-1 font-mono">@{entry.Name}</span>
							<span class="text-muted-foreground">{formatNumber(entry.Count)} reviews</span>
						</a>
					{/each}
				</CardContent>
			</Card>
		{/if}
		{#if d?.GatekeeperBoard?.length > 0}
			<Card>
				<CardHeader><CardTitle class="text-sm">Gatekeepers</CardTitle></CardHeader>
				<CardContent class="space-y-1">
					{#each d.GatekeeperBoard as entry}
						<a href="/user/{entry.Name}" class="flex items-center gap-2 rounded px-1 py-0.5 text-xs hover:bg-accent">
							<span class="w-7 shrink-0 {rankClass(entry.Rank)}">#{entry.Rank}</span>
							{#if entry.Extra}<img src={entry.Extra} alt="" class="size-4 rounded-full" />{/if}
							<span class="flex-1 font-mono">@{entry.Name}</span>
							<span class="text-muted-foreground">{formatNumber(entry.Count)} blocks</span>
						</a>
					{/each}
				</CardContent>
			</Card>
		{/if}
	</div>
{/if}

<!-- Repos -->
{#if d?.Repos?.length > 0}
	<Card>
		<CardHeader><CardTitle class="text-sm">Org Repos</CardTitle></CardHeader>
		<CardContent class="overflow-x-auto p-0">
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead>Repo</TableHead>
						<TableHead class="w-24">Merged PRs</TableHead>
						<TableHead class="w-28">Avg Time</TableHead>
						<TableHead class="w-20">Stars</TableHead>
					</TableRow>
				</TableHeader>
				<TableBody>
					{#each d.Repos as repo}
						<TableRow>
							<TableCell class="font-mono text-xs">
								<a href="/repo/{repo.FullName}" class="hover:underline">{repo.FullName}</a>
							</TableCell>
							<TableCell class="text-xs">{formatNumber(repo.MergedPRCount)}</TableCell>
							<TableCell class="text-xs">{repo.AvgMergeTimeSecs ? formatDuration(repo.AvgMergeTimeSecs) : '—'}</TableCell>
							<TableCell class="text-xs text-muted-foreground">{repo.Stars ? `${formatNumber(repo.Stars)} ★` : ''}</TableCell>
						</TableRow>
					{/each}
				</TableBody>
			</Table>
		</CardContent>
	</Card>
{/if}

// frontend/app/org/[org]/page.tsx
import Link from "next/link";
import { redirect } from "next/navigation";

import { TimeCharts, type TimePayload } from "@/components/Charts";
import { apiGet, qs } from "@/lib/api";
import { formatDuration, formatNumber, jsonPayload, rankBadge, rankClass } from "@/lib/format";
import type { OrgData } from "@/types/api";

type Props = {
  params: Promise<{ org: string }>;
  searchParams: Promise<{ trim?: string }>;
};

export default async function OrgPage({ params, searchParams }: Props) {
  const { org } = await params;
  const sp = await searchParams;
  const trim = Number(sp.trim || 0);
  const data = await apiGet<OrgData>(`/api/next/org/${org}${qs({ trim })}`);
  if (data.redirect) redirect(data.redirect);
  const time = jsonPayload<TimePayload>(data.TimeChartJSON);

  return (
    <div className="page-wrap">
      <div className="user-header">
        {data.Org.AvatarURL ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={data.Org.AvatarURL} className="user-avatar" alt={data.Org.Login} />
        ) : null}
        <div className="user-info">
          <div className="org-type-badge">Organization</div>
          <h1 className="page-title">{data.Org.Name || data.Org.Login}</h1>
          <p className="user-login mono">@{data.Org.Login}</p>
          {data.Org.Bio ? <p className="user-bio">{data.Org.Bio}</p> : null}
          <div className="user-meta">
            {data.TotalMergedPRs ? <span>{formatNumber(data.TotalMergedPRs)} merged PRs tracked</span> : null}
            {data.Org.PublicRepos ? <span>{formatNumber(data.Org.PublicRepos)} public repos</span> : null}
          </div>
        </div>
        <a href={`https://github.com/${data.Org.Login}`} target="_blank" rel="noopener" className="btn btn-outline">
          GitHub ↗
        </a>
      </div>

      <TimeCharts payload={time} />

      <div className="two-col">
        <OrgBoard title="In-Org Review Champions" entries={data.ReviewerBoard} suffix="reviews" />
        <OrgBoard title="In-Org Gatekeepers" entries={data.GatekeeperBoard} suffix="blocks" warn />
      </div>

      <section className="section">
        <h2 className="section-title">Repos</h2>
        {data.Repos?.length ? (
          <div className="org-repos">
            {data.Repos.map((repo) => (
              <Link href={`/repo/${repo.FullName}`} className="org-repo-card" key={repo.FullName}>
                <div className="org-repo-top">
                  <span className="org-repo-name mono">{repo.Name}</span>
                  {repo.Language ? <span className="lang-badge sm">{repo.Language}</span> : null}
                  {repo.Stars ? <span className="stars-badge sm">{formatNumber(repo.Stars)} stars</span> : null}
                  {repo.SyncStatus ? <span className={`sync-badge ${repo.SyncStatus} sm`}>{repo.SyncStatus}</span> : null}
                </div>
                {repo.Description ? <p className="org-repo-desc">{repo.Description}</p> : null}
                {repo.MergedPRCount ? (
                  <div className="org-repo-stats">
                    <span>{formatNumber(repo.MergedPRCount)} merged PRs</span>
                    <span> · </span>
                    <span>avg {formatDuration(repo.AvgMergeTimeSecs)}</span>
                    <span> · </span>
                    <span>fastest {formatDuration(repo.MinMergeTimeSecs)}</span>
                  </div>
                ) : null}
              </Link>
            ))}
          </div>
        ) : (
          <div className="empty-state">
            <p>Syncing top repos for {data.Org.Login}... check back in a moment.</p>
          </div>
        )}
      </section>
    </div>
  );
}

function OrgBoard({ title, entries, suffix, warn = false }: { title: string; entries?: OrgData["ReviewerBoard"]; suffix: string; warn?: boolean }) {
  return (
    <div className="col-card">
      <h2 className="col-title">{title}</h2>
      {entries?.length ? (
        <div className="board-rows">
          {entries.map((entry) => (
            <Link href={`/user/${entry.Name}`} className="board-row" key={entry.Name}>
              <span className={`board-rank ${rankClass(entry.Rank)}`}>{rankBadge(entry.Rank)}</span>
              {entry.Extra ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={entry.Extra} className="board-avatar" alt="" />
              ) : null}
              <span className="board-name mono">@{entry.Name}</span>
              <span className={`board-val ${warn ? "warn" : ""}`}>
                {formatNumber(entry.Count)} {suffix}
              </span>
            </Link>
          ))}
        </div>
      ) : (
        <p className="col-empty">No data yet.</p>
      )}
    </div>
  );
}
